name: 'Setup Server Dependencies'
description: 'Sets up the server dependencies required for the testing containers.'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
        cache-dependency-path: server/pnpm-lock.yaml

    - name: Install Dependencies
      shell: bash
      run: pnpm install
      working-directory: ./server
