name: 'Setup Environment Variables'
description: 'Sets up the environment variables required for the testing containers.'

inputs:
  AUTH_GOOGLE_ID:
    description: Google OAuth Client ID
    required: true
  AUTH_GOOGLE_SECRET:
    description: Google OAuth Client Secret
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create env directory
      shell: bash
      run: mkdir env

    - name: Create server.env file
      shell: bash
      run: |
        touch server.env
        echo 'DATABASE_URL=postgres://postgres:postgres@database:5432/bridges' >> server.env
        cat server.env
      working-directory: ./env

    - name: Create client.env file
      shell: bash
      run: |
        touch client.env
        echo 'AUTH_SECRET="'$(openssl rand -base64 32)'"' >> client.env
        echo 'AUTH_GOOGLE_ID=${{ inputs.AUTH_GOOGLE_ID }}' >> client.env
        echo 'AUTH_GOOGLE_SECRET=${{ inputs.AUTH_GOOGLE_SECRET }}' >> client.env
      working-directory: ./env
